package com.myInventory.model;


import jakarta.persistence.*;

import java.io.Serializable;

@Entity
// Defines a table at the class level
@Table
public class Client implements Serializable {

    // Will be the unique id generated for this object
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // To manage two or more users editing the same thing
    @Version
    private Integer version;

    // Defining attributes that will belong to the object Client
    private String company;
    private String fistName;
    private String lastName;
    private String address;
    private String city;
    private String stateinitial;
    private int zip;
    private String phoneNumber;

    // Default constructor
    public Client() {
    }

    // Getters and setters generated by the IDE
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getFistName() {
        return fistName;
    }

    public void setFistName(String fistName) {
        this.fistName = fistName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStateinitial() {
        return stateinitial;
    }

    public void setStateinitial(String stateinitial) {
        this.stateinitial = stateinitial;
    }

    public int getZip() {
        return zip;
    }

    public void setZip(int zip) {
        this.zip = zip;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getModel() {
        throw new UnsupportedOperationException("Not supported yet."); // To change body of generated methods, choose Tools | Templates
    }
}
