package com.myInventory.model;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.math.BigDecimal;

@Entity
// Defines table with the name 'products'
@Table(name = "products")
public class Product implements Serializable {

    // Will be the unique id generated for this object
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Will be the unique id generated for this object
    @Version
    private Integer version;

    // Manufacturer up to 20 characters, non empty
    @NotBlank
    @Column(nullable = false, length = 20)
    private String manufacturer;

    // Model up to 50 characters, non empty
    @NotBlank
    @Column(nullable = false, length = 50)
    private String model;

    // Description up to 256 characters non empty
    @NotBlank
    @Column(nullable = false, length = 256)
    private String description;

    // Cost for the company, formatted as money, not null
    @NotNull
    @Column(nullable = false, length = 12, scale = 2, precision = 8)
    private BigDecimal cost;

    // List Price sold to the customer, formatted as money, not null
    @NotNull
    @Column(nullable = false, length = 12, scale = 2, precision = 8)
    private BigDecimal listPrice;

    // Default constructor
    public Product() {
    }

    // Parameterized constructor
    public Product(Long id, String manufacturer, String model,
            String description, BigDecimal listPrice) {
        this.id = id;
        this.manufacturer = manufacturer;
        this.model = model;
        this.description = description;
        this.listPrice = listPrice;
    }

    // Getters and Setters generated by the IDE

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public BigDecimal getListPrice() {
        return listPrice;
    }

    public void setListPrice(BigDecimal listPrice) {
        this.listPrice = listPrice;
    }


}
